### ISSUE TITLE
JSL missing?

### ISSUE THREAD

**Issue by CdRGit** [maxbane/vim-syntax-asm_ca65#5]
the 65816 mnemonic JSL appears to be missing, is this intentional or was this a mistake?

**Comment by maxbane** [comment]
Thanks for reaching out! It's just an oversight... or rather, currently none of the 65816-specific mnemonics is supported. Looking around [line 72](https://github.com/maxbane/vim-asm_ca65/blob/master/syntax/asm_ca65.vim#L72) of the syntax file, it seems I've defined groups of mnemonic keywords for the base 6502, the "WDC" and "Rockwell" variant mnemonics, and the ca65 "macpack" of [generic built-in macros](https://cc65.github.io/doc/ca65.html#ss13.1). Highlighting of these keywords (other than the base 6502 mnemonics, which are always highlighted) is then enabled by setting global vim flags as seen around [line 288](https://github.com/maxbane/vim-asm_ca65/blob/master/syntax/asm_ca65.vim#L288).

It seems I simply never included an analogous group of keywords for the 65816 mnemonics, nor a flag for highlighting them. Should be straightforward, but I may not get to in a while... happy to accept a PR for it, though.

**Comment by CdRGit** [comment]
the 65816 mnemonics are already in the "WDC" block, such as JML, MVP, MVN, XBA, XCE, SEP, REP and others, none of those are part of the W65C02 (XCE is in fact the 'start/stop behaving like a 65C816' mnemonic)

**Comment by maxbane** [comment]
Aha! You're quite right. Sorry, trying to remember what I did 7 years ago :). It looks like all of the 16-bit mnemonics are in that "WDC" group, in which case the absence of JSL is certainly a mistake. I should reorganize these keyword groups to align with actual processor names, but in the meantime I can quickly add JSL to the existing "WDC" list.

**Comment by maxbane** [comment]
Fixed with commit 59f2f5ea1adb2fa321b62c3f0817545abb836b09, added issue #6 for a more sensible reorganization of the highlightable keywords.
